spring:
  application:
    name: microservice-api-gateway
  datasource:
    url: jdbc:mysql://localhost:3306/strking_db?useUnicode=true&characterEncoding=UTF-8&ssl=false
    username: root
    passWord: root
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  mapper-locations: classpath:mapper/*.xml
server:
  port: 3333
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/

##jwt配置
audience:
  clientId: 098f6bcd4621d373cade4e832627b4f6
  base64Secret: MDk4ZjZiY2Q0NjIxZDM3M2NhZGU0ZTgzMjYyN2I0ZjY=
  name: restapiuser
  expiresSecond: 172800

zuul:
  host:
    connect-timeout-millis: 10000
    socket-timeout-millis: 60000